const datosProductosPoliester = [
  {
    image: "/POLIESTER.jpg",
    text: "ENTONADOR PS NEGRO",
    description: "",

    type: "Poliester",
    pdf: "/fichastecnicas/Barnices/FT BARNIZ HS.pdf",
  },
  {
    image: "/POLIESTER.jpg",
    text: "ENTONADOR PS BLANCO",
    description: "",

    type: "Poliester",
    pdf: "/fichastecnicas/Barnices/FT BARNIZ PLUS 2K.pdf",
  },
  {
    image: "/POLIESTER.jpg",
    text: "ADITIVO DE EFECTO",
    description: "",
    type: "Poliester",
    pdf: "/fichastecnicas/Barnices/FT BARNIZ EXPRESS.pdf",
  },
  {
    image: "/POLIESTER.jpg",
    text: "ENTONADOR PS ROJO LIMPIO",
    description: "",
    type: "Poliester",
    pdf: "/fichastecnicas/AnticorrosivosEpoxicos/FT AUTOIMPRIMANTE GRIS.pdf",
  },
  {
    image: "/POLIESTER.jpg",
    text: "ENTONADOR PS VERDE AZULOSO",
    description: "",
    type: "Poliester",
    pdf: "/fichastecnicas/AnticorrosivosEpoxicos/FT AUTOIMPRIMANTE GRIS.pdf",
  },
  {
    image: "/POLIESTER.jpg",
    text: "ALUMINIO FINO",
    description: "",
    type: "Poliester",
    pdf: "/fichastecnicas/AnticorrosivosEpoxicos/FT AUTOIMPRIMANTE GRIS.pdf",
  },
  {
    image: "/POLIESTER.jpg",
    text: "ALUMINIO MEDIO",
    description: "",
    type: "Poliester",
    pdf: "/fichastecnicas/AnticorrosivosEpoxicos/FT AUTOIMPRIMANTE GRIS.pdf",
  },
  {
    image: "/POLIESTER.jpg",
    text: "ENTONADOR PS AZUL",
    description: "",
    type: "Poliester",
    pdf: "/fichastecnicas/AnticorrosivosEpoxicos/FT AUTOIMPRIMANTE GRIS.pdf",
  },
  {
    image: "/POLIESTER.jpg",
    text: "ENTONADOR PS VIOLETA ROJIZO",
    description: "",
    type: "Poliester",
    pdf: "/fichastecnicas/Diluyentesycomplementarios/FT DILUYENTE PUR ATL.pdf",
  },
  {
    image: "/POLIESTER.jpg",
    text: "ALUMINIO FINO LENTICULAR",
    description: "",
    type: "Poliester",
    pdf: "/fichastecnicas/Diluyentesycomplementarios/FT DESENGRASANTE B.S.pdf",
  },
  {
    image: "/POLIESTER.jpg",
    text: "ALUMINIO MEDIO LENTICULAR",
    description: "",
    type: "Poliester",
    pdf: "/fichastecnicas/Diluyentesycomplementarios/FT REMOVEDOR DE OXIDO.pdf",
  },
  {
    image: "/POLIESTER.jpg",
    text: "ENTONADOR PS BLANCO TRANSPARENTE",
    description: "",
    type: "Poliester",
    pdf: "/fichastecnicas/Diluyentesycomplementarios/FT SLN EPOXICA.pdf",
  },
  {
    image: "/POLIESTER.jpg",
    text: "ENTONADOR PS VIOLETA AZULOSO",
    description: "",
    type: "Poliester",
    pdf: "/fichastecnicas/Diluyentesycomplementarios/FT SOLUCIÓN POLIURETANICA.pdf",
  },
  {
    image: "/POLIESTER.jpg",
    text: "ENTONADOR PS AZUL INDIO",
    description: "",
    type: "Poliester",
    pdf: "/fichastecnicas/Entonadoresps/FT ENTONADORES PS.pdf",
  },
  {
    image: "/POLIESTER.jpg",
    text: "ENTONADOR PS MARRÓN",
    description: "",
    type: "Poliester",
    pdf: "/fichastecnicas/AnticorrosivosEpoxicos/FT AUTOIMPRIMANTE GRIS.pdf",
  },
  {
    image: "/POLIESTER.jpg",
    text: "ALUMINIO GRUESO",
    description: "",
    type: "Poliester",
    pdf: "/fichastecnicas/AnticorrosivosEpoxicos/FT AUTOIMPRIMANTE GRIS.pdf",
  },
  {
    image: "/POLIESTER.jpg",
    text: "ENTONADOR PS AMARILLO LIMON",
    description: "",
    type: "Poliester",
    pdf: "/fichastecnicas/AnticorrosivosEpoxicos/FT AUTOIMPRIMANTE GRIS.pdf",
  },
  {
    image: "/POLIESTER.jpg",
    text: "PERLA AZUL",
    description: "",
    type: "Poliester",
    pdf: "/fichastecnicas/AnticorrosivosEpoxicos/FT AUTOIMPRIMANTE GRIS.pdf",
  },
  {
    image: "/POLIESTER.jpg",
    text: "PERLA VIOLETA",
    description: "",
    type: "Poliester",
    pdf: "/fichastecnicas/AnticorrosivosEpoxicos/FT AUTOIMPRIMANTE GRIS.pdf",
  },
  {
    image: "/POLIESTER.jpg",
    text: "ALUMINIO GRUESO LENTICULAR ",
    description: "",
    type: "Poliester",
    pdf: "/fichastecnicas/AnticorrosivosEpoxicos/FT EPOXICO ANTICORROSIVOS.pdf",
  },
  {
    image: "/POLIESTER.jpg",
    text: "PERLA VERDE",
    description: "",
    type: "Poliester",
    pdf: "/fichastecnicas/AnticorrosivosEpoxicos/FT WASH PRIMER.pdf",
  },
  {
    image: "/POLIESTER.jpg",
    text: "PERLA BLANCA",
    description: "",
    type: "Poliester",
    pdf: "/fichastecnicas/AnticorrosivosEpoxicos/FT AUTOIMPRIMANTE GRIS.pdf",
  },
  {
    image: "/POLIESTER.jpg",
    text: "ENTONADOR PS AMARILLO TRANSPARENTE",
    description: "",
    type: "Poliester",
    pdf: "/fichastecnicas/AnticorrosivosEpoxicos/FT AUTOIMPRIMANTE GRIS.pdf",
  },
  {
    image: "/POLIESTER.jpg",
    text: "ENTONADOR PS ROJO",
    description: "",
    type: "Poliester",
    pdf: "/fichastecnicas/AnticorrosivosEpoxicos/FT AUTOIMPRIMANTE GRIS.pdf",
  },
  {
    image: "/POLIESTER.jpg",
    text: "ENTONADOR PS AMARILLO OXIDO",
    description: "",
    type: "Poliester",
    pdf: "/fichastecnicas/AnticorrosivosEpoxicos/FT AUTOIMPRIMANTE GRIS.pdf",
  },
  {
    image: "/POLIESTER.jpg",
    text: "ENTONADOR PS ROJO TRANSPARENTE",
    description: "",
    type: "Poliester",
    pdf: "/fichastecnicas/AnticorrosivosEpoxicos/FT AUTOIMPRIMANTE GRIS.pdf",
  },
  {
    image: "/POLIESTER.jpg",
    text: "SOLUCION PS TTE",
    description: "",
    type: "Poliester",
    pdf: "/fichastecnicas/AnticorrosivosEpoxicos/FT AUTOIMPRIMANTE GRIS.pdf",
  },
  {
    image: "/POLIESTER.jpg",
    text: "PERLA ROJA",
    description: "",
    type: "Poliester",
    pdf: "/fichastecnicas/AnticorrosivosEpoxicos/FT AUTOIMPRIMANTE GRIS.pdf",
  },
  {
    image: "/POLIESTER.jpg",
    text: "PERLA ROJA AURALICX",
    description: "",
    type: "Poliester",
    pdf: "/fichastecnicas/AnticorrosivosEpoxicos/FT AUTOIMPRIMANTE GRIS.pdf",
  },
  {
    image: "/POLIESTER.jpg",
    text: "PERLA COBRE AURALICX",
    description: "",
    type: "Poliester",
    pdf: "/fichastecnicas/AnticorrosivosEpoxicos/FT AUTOIMPRIMANTE GRIS.pdf",
  },
  {
    image: "/POLIESTER.jpg",
    text: "PERLA AZUL AURALICX",
    description: "",
    type: "Poliester",
    pdf: "/fichastecnicas/AnticorrosivosEpoxicos/FT AUTOIMPRIMANTE GRIS.pdf",
  },
  {
    image: "/POLIESTER.jpg",
    text: "PERLA VERDE AURALICX",
    description: "",
    type: "Poliester",
    pdf: "/fichastecnicas/AnticorrosivosEpoxicos/FT AUTOIMPRIMANTE GRIS.pdf",
  },
  {
    image: "/POLIESTER.jpg",
    text: "PERLA BLANCA AURALICX",
    description: "",
    type: "Poliester",
    pdf: "/fichastecnicas/AnticorrosivosEpoxicos/FT AUTOIMPRIMANTE GRIS.pdf",
  },
];

export default datosProductosPoliester;
