const datosProductoPoliuretano = [
  {
    image: "/POLIURETANO.jpg",
    text: "ENTONADOR PUR BLANCO",
    description: "",

    type: "Poliuretano",
    pdf: "/fichastecnicas/Barnices/FT BARNIZ HS.pdf",
  },
  {
    image: "/POLIURETANO.jpg",
    text: "ENTONADOR PUR AMARILLO CROMO",
    description: "",

    type: "Poliuretano",
    pdf: "/fichastecnicas/Barnices/FT BARNIZ PLUS 2K.pdf",
  },
  {
    image: "/POLIURETANO.jpg",
    text: "ENTONADOR PUR NARANJA",
    description: "",
    type: "Poliuretano",
    pdf: "/fichastecnicas/Barnices/FT BARNIZ EXPRESS.pdf",
  },
  {
    image: "/POLIURETANO.jpg",
    text: "ENTONADOR PUR VIOLETA ROJIZO",
    description: "",
    type: "Poliuretano",
    pdf: "/fichastecnicas/AnticorrosivosEpoxicos/FT AUTOIMPRIMANTE GRIS.pdf",
  },
  {
    image: "/POLIURETANO.jpg",
    text: "ENTONADOR PUR AMARILLO VERDOSO",
    description: "",
    type: "Poliuretano",
    pdf: "/fichastecnicas/AnticorrosivosEpoxicos/FT AUTOIMPRIMANTE GRIS.pdf",
  },
  {
    image: "/POLIURETANO.jpg",
    text: "ESMALTE PUR NEGRO MATE",
    description: "",
    type: "Poliuretano",
    pdf: "/fichastecnicas/AnticorrosivosEpoxicos/FT AUTOIMPRIMANTE GRIS.pdf",
  },
  {
    image: "/POLIURETANO.jpg",
    text: "ENTONADOR PUR AZUL",
    description: "",
    type: "Poliuretano",
    pdf: "/fichastecnicas/AnticorrosivosEpoxicos/FT AUTOIMPRIMANTE GRIS.pdf",
  },
  {
    image: "/POLIURETANO.jpg",
    text: "ENTONADOR PUR AMARILLO ROJIZO",
    description: "",
    type: "Poliuretano",
    pdf: "/fichastecnicas/AnticorrosivosEpoxicos/FT AUTOIMPRIMANTE GRIS.pdf",
  },
  {
    image: "/POLIURETANO.jpg",
    text: "ENTONADOR PUR NEGRO",
    description: "",
    type: "Poliuretano",
    pdf: "/fichastecnicas/Diluyentesycomplementarios/FT DILUYENTE PUR ATL.pdf",
  },
  {
    image: "/POLIURETANO.jpg",
    text: "FONDO GRIS PUR 2K",
    description: "",
    type: "Poliuretano",
    pdf: "/fichastecnicas/Diluyentesycomplementarios/FT DESENGRASANTE B.S.pdf",
  },
  {
    image: "/POLIURETANO.jpg",
    text: "ENTONADOR PUR ROJO",
    description: "",
    type: "Poliuretano",
    pdf: "/fichastecnicas/Diluyentesycomplementarios/FT REMOVEDOR DE OXIDO.pdf",
  },
  {
    image: "/POLIURETANO.jpg",
    text: "ENTONADOR PUR VERDE",
    description: "",
    type: "Poliuretano",
    pdf: "/fichastecnicas/Diluyentesycomplementarios/FT SLN EPOXICA.pdf",
  },
  {
    image: "/POLIURETANO.jpg",
    text: "ENTONADOR PUR ROJO OXIDO",
    description: "",
    type: "Poliuretano",
    pdf: "/fichastecnicas/Diluyentesycomplementarios/FT SOLUCIÓN POLIURETANICA.pdf",
  },
  {
    image: "/POLIURETANO.jpg",
    text: "ENTONADOR PUR AMARILLO OXIDO",
    description: "",
    type: "Poliuretano",
    pdf: "/fichastecnicas/Entonadoresps/FT ENTONADORES PS.pdf",
  },
  {
    image: "/POLIURETANO.jpg",
    text: "FONDO BLANCO PUR 2K",
    description: "",
    type: "Poliuretano",
    pdf: "/fichastecnicas/AnticorrosivosEpoxicos/FT AUTOIMPRIMANTE GRIS.pdf",
  },
  {
    image: "/POLIURETANO.jpg",
    text: "FONDO NEGRO PUR 2K",
    description: "",
    type: "Poliuretano",
    pdf: "/fichastecnicas/AnticorrosivosEpoxicos/FT AUTOIMPRIMANTE GRIS.pdf",
  },
  {
    image: "/POLIURETANO.jpg",
    text: "ENTONADOR PUR AMARILLO LIMON",
    description: "",
    type: "Poliuretano",
    pdf: "/fichastecnicas/AnticorrosivosEpoxicos/FT AUTOIMPRIMANTE GRIS.pdf",
  },
  {
    image: "/POLIURETANO.jpg",
    text: "ENTONADOR PUR VIOLETA AZULOSO",
    description: "",
    type: "Poliuretano",
    pdf: "/fichastecnicas/AnticorrosivosEpoxicos/FT AUTOIMPRIMANTE GRIS.pdf",
  },
  {
    image: "/POLIURETANO.jpg",
    text: "ENTONADOR PUR ROJO LIMPIO",
    description: "",
    type: "Poliuretano",
    pdf: "/fichastecnicas/AnticorrosivosEpoxicos/FT AUTOIMPRIMANTE GRIS.pdf",
  },
  {
    image: "/POLIURETANO.jpg",
    text: "PASTA MATEANTE",
    description: "",
    type: "Poliuretano",
    pdf: "/fichastecnicas/AnticorrosivosEpoxicos/FT EPOXICO ANTICORROSIVOS.pdf",
  },
  {
    image: "/POLIURETANO.jpg",
    text: "ESMALTE PUR BLANCO MATE",
    description: "",
    type: "Poliuretano",
    pdf: "/fichastecnicas/AnticorrosivosEpoxicos/FT WASH PRIMER.pdf",
  },
  {
    image: "/POLIURETANO.jpg",
    text: "ESMALTE PUR METALIZADO GRUESO",
    description: "",
    type: "Poliuretano",
    pdf: "/fichastecnicas/AnticorrosivosEpoxicos/FT AUTOIMPRIMANTE GRIS.pdf",
  },
  {
    image: "/POLIURETANO.jpg",
    text: "ESMALTE PUR METALIZADO FINO",
    description: "",
    type: "Poliuretano",
    pdf: "/fichastecnicas/AnticorrosivosEpoxicos/FT AUTOIMPRIMANTE GRIS.pdf",
  },
  {
    image: "/POLIURETANO.jpg",
    text: "ESMALTE PUR NEGRO SEMIMATE",
    description: "",
    type: "Poliuretano",
    pdf: "/fichastecnicas/AnticorrosivosEpoxicos/FT AUTOIMPRIMANTE GRIS.pdf",
  },
  {
    image: "/POLIURETANO.jpg",
    text: "ESMALTE PUR ROJO FERRARI",
    description: "",
    type: "Poliuretano",
    pdf: "/fichastecnicas/AnticorrosivosEpoxicos/FT AUTOIMPRIMANTE GRIS.pdf",
  },
  {
    image: "/POLIURETANO.jpg",
    text: "FONDO AMARILLO PUR 2K",
    description: "",
    type: "Poliuretano",
    pdf: "/fichastecnicas/AnticorrosivosEpoxicos/FT AUTOIMPRIMANTE GRIS.pdf",
  },
  {
    image: "/POLIURETANO.jpg",
    text: "ESMALTE PUR BLANCO SEMIMATE",
    description: "",
    type: "Poliuretano",
    pdf: "/fichastecnicas/AnticorrosivosEpoxicos/FT AUTOIMPRIMANTE GRIS.pdf",
  },
  {
    image: "/POLIURETANO.jpg",
    text: "ENTONADOR PUR ROJO TRANSPARENTE",
    description: "",
    type: "Poliuretano",
    pdf: "/fichastecnicas/AnticorrosivosEpoxicos/FT AUTOIMPRIMANTE GRIS.pdf",
  },
  {
    image: "/POLIURETANO.jpg",
    text: "BARNIZ PLUS 2K",
    description: "",
    type: "Poliuretano",
    pdf: "/fichastecnicas/AnticorrosivosEpoxicos/FT AUTOIMPRIMANTE GRIS.pdf",
  },
  {
    image: "/POLIURETANO.jpg",
    text: "BARNIZ EXPRESS",
    description: "",
    type: "Poliuretano",
    pdf: "/fichastecnicas/AnticorrosivosEpoxicos/FT AUTOIMPRIMANTE GRIS.pdf",
  },
  {
    image: "/POLIURETANO.jpg",
    text: "BARNIZ MATE",
    description: "",
    type: "Poliuretano",
    pdf: "/fichastecnicas/AnticorrosivosEpoxicos/FT AUTOIMPRIMANTE GRIS.pdf",
  },
  {
    image: "/POLIURETANO.jpg",
    text: "BARNIZ ALTOS SOLIDOS",
    description: "",
    type: "Poliuretano",
    pdf: "/fichastecnicas/AnticorrosivosEpoxicos/FT AUTOIMPRIMANTE GRIS.pdf",
  },
  {
    image: "/POLIURETANO.jpg",
    text: "BARNIZ SEMIMATE",
    description: "",
    type: "Poliuretano",
    pdf: "/fichastecnicas/AnticorrosivosEpoxicos/FT AUTOIMPRIMANTE GRIS.pdf",
  },
];

export default datosProductoPoliuretano;
