const datosProductoIndustria = [
  {
    image: "/INDUSTRIA.jpg",
    text: "PUR NEGRO MATE DTM",
    description: "",

    type: "Industrial",
    pdf: "/fichastecnicas/Barnices/FT BARNIZ HS.pdf",
  },
  {
    image: "/INDUSTRIA.jpg",
    text: "PUR BLANCO MATE DTM",
    description: "",

    type: "Industrial",
    pdf: "/fichastecnicas/Barnices/FT BARNIZ PLUS 2K.pdf",
  },
  {
    image: "/INDUSTRIA.jpg",
    text: "ESMALTE PUR BEIGE DTM ",
    description: "",
    type: "Industrial",
    pdf: "/fichastecnicas/Barnices/FT BARNIZ EXPRESS.pdf",
  },
  {
    image: "/INDUSTRIA.jpg",
    text: "ESMALTE PUR GRIS MATE DTM",
    description: "",
    type: "Industrial",
    pdf: "/fichastecnicas/AnticorrosivosEpoxicos/FT AUTOIMPRIMANTE GRIS.pdf",
  },
  {
    image: "/INDUSTRIA.jpg",
    text: "ESMALTE PUR GRIS PLATA",
    description: "",
    type: "Industrial",
    pdf: "/fichastecnicas/AnticorrosivosEpoxicos/FT AUTOIMPRIMANTE GRIS.pdf",
  },
  {
    image: "/INDUSTRIA.jpg",
    text: "ESMALTE MONOCOMPONENTE AMARILLO",
    description: "",
    type: "Industrial",
    pdf: "/fichastecnicas/AnticorrosivosEpoxicos/FT AUTOIMPRIMANTE GRIS.pdf",
  },
  {
    image: "/INDUSTRIA.jpg",
    text: "ESMALTE PUR ROJO DTM",
    description: "",
    type: "Industrial",
    pdf: "/fichastecnicas/AnticorrosivosEpoxicos/FT AUTOIMPRIMANTE GRIS.pdf",
  },
  {
    image: "/INDUSTRIA.jpg",
    text: "ESMALTE PUR AZUL DTM",
    description: "",
    type: "Industrial",
    pdf: "/fichastecnicas/AnticorrosivosEpoxicos/FT AUTOIMPRIMANTE GRIS.pdf",
  },
  {
    image: "/INDUSTRIA.jpg",
    text: "ESMALTE PUR BLANCO DTM",
    description: "",
    type: "Industrial",
    pdf: "/fichastecnicas/Diluyentesycomplementarios/FT DILUYENTE PUR ATL.pdf",
  },
  {
    image: "/INDUSTRIA.jpg",
    text: "ESMALTE PUR NEGRO DTM",
    description: "",
    type: "Industrial",
    pdf: "/fichastecnicas/Diluyentesycomplementarios/FT DESENGRASANTE B.S.pdf",
  },
  {
    image: "/INDUSTRIA.jpg",
    text: "ESMALTE PUR VERDE DTM",
    description: "",
    type: "Industrial",
    pdf: "/fichastecnicas/Diluyentesycomplementarios/FT REMOVEDOR DE OXIDO.pdf",
  },
  {
    image: "/INDUSTRIA.jpg",
    text: "ESMALTE PUR AMARILLO ROJIZO DTM",
    description: "",
    type: "Industrial",
    pdf: "/fichastecnicas/Diluyentesycomplementarios/FT SLN EPOXICA.pdf",
  },
  {
    image: "/INDUSTRIA.jpg",
    text: "ESMALTE PUR AMARILLO OXIDO DTM",
    description: "",
    type: "Industrial",
    pdf: "/fichastecnicas/Diluyentesycomplementarios/FT SOLUCIÓN POLIURETANICA.pdf",
  },
  {
    image: "/INDUSTRIA.jpg",
    text: "ESMALTE PUR NARANJA DTM",
    description: "",
    type: "Industrial",
    pdf: "/fichastecnicas/Entonadoresps/FT ENTONADORES PS.pdf",
  },
  {
    image: "/INDUSTRIA.jpg",
    text: "ESMALTE PUR ROJO LIMPIO MATE DTM",
    description: "",
    type: "Industrial",
    pdf: "/fichastecnicas/AnticorrosivosEpoxicos/FT AUTOIMPRIMANTE GRIS.pdf",
  },
  {
    image: "/INDUSTRIA.jpg",
    text: "ESMALTE EPÓXICO INDUSTRIAL GRIS",
    description: "",
    type: "Industrial",
    pdf: "/fichastecnicas/AnticorrosivosEpoxicos/FT AUTOIMPRIMANTE GRIS.pdf",
  },
  {
    image: "/INDUSTRIA.jpg",
    text: "ESMALTE EPÓXICO INDUSTRIAL ROJO",
    description: "",
    type: "Industrial",
    pdf: "/fichastecnicas/AnticorrosivosEpoxicos/FT AUTOIMPRIMANTE GRIS.pdf",
  },
  {
    image: "/INDUSTRIA.jpg",
    text: "ESMALTE EPÓXICO INDUSTRIAL BEIGE",
    description: "",
    type: "Industrial",
    pdf: "/fichastecnicas/AnticorrosivosEpoxicos/FT AUTOIMPRIMANTE GRIS.pdf",
  },
  {
    image: "/INDUSTRIA.jpg",
    text: "ESMALTE EPÓXICO INDUSTRIAL BLANCO",
    description: "",
    type: "Industrial",
    pdf: "/fichastecnicas/AnticorrosivosEpoxicos/FT AUTOIMPRIMANTE GRIS.pdf",
  },
  {
    image: "/INDUSTRIA.jpg",
    text: "ESMALTE EPÓXICO INDUSTRIAL BLANCO MATE",
    description: "",
    type: "Industrial",
    pdf: "/fichastecnicas/AnticorrosivosEpoxicos/FT AUTOIMPRIMANTE GRIS.pdf",
  },
  {
    image: "/INDUSTRIA.jpg",
    text: "FONDO EPÓXICO ANTICORROSIVO AZUL",
    description: "",
    type: "Industrial",
    pdf: "/fichastecnicas/AnticorrosivosEpoxicos/FT AUTOIMPRIMANTE GRIS.pdf",
  },
  {
    image: "/INDUSTRIA.jpg",
    text: "FONDO  EPÓXICO ANTICORROSIVO VERDE",
    description: "",
    type: "Industrial",
    pdf: "/fichastecnicas/AnticorrosivosEpoxicos/FT AUTOIMPRIMANTE GRIS.pdf",
  },
  {
    image: "/INDUSTRIA.jpg",
    text: "ESMALTE EPÓXICO INDUSTRIAL AMARILLO CROMO",
    description: "",
    type: "Industrial",
    pdf: "/fichastecnicas/AnticorrosivosEpoxicos/FT AUTOIMPRIMANTE GRIS.pdf",
  },
  {
    image: "/INDUSTRIA.jpg",
    text: "WASH PRIMER",
    description: "",
    type: "Industrial",
    pdf: "/fichastecnicas/AnticorrosivosEpoxicos/FT AUTOIMPRIMANTE GRIS.pdf",
  },
  {
    image: "/INDUSTRIA.jpg",
    text: "AUTOIMPRIMANTE GRIS",
    description: "",
    type: "Industrial",
    pdf: "/fichastecnicas/AnticorrosivosEpoxicos/FT AUTOIMPRIMANTE GRIS.pdf",
  },
  {
    image: "/INDUSTRIA.jpg",
    text: "ESMALTE EPÓXICO INDUSTRIAL AZUL",
    description: "",
    type: "Industrial",
    pdf: "/fichastecnicas/AnticorrosivosEpoxicos/FT AUTOIMPRIMANTE GRIS.pdf",
  },
  {
    image: "/INDUSTRIA.jpg",
    text: "ESMALTE EPÓXICO INDUSTRIAL NEGRO",
    description: "",
    type: "Industrial",
    pdf: "/fichastecnicas/AnticorrosivosEpoxicos/FT AUTOIMPRIMANTE GRIS.pdf",
  },
  {
    image: "/INDUSTRIA.jpg",
    text: "ESMALTE EPÓXICO INDUSTRIAL AZUL OSCURO",
    description: "",
    type: "Industrial",
    pdf: "/fichastecnicas/AnticorrosivosEpoxicos/FT AUTOIMPRIMANTE GRIS.pdf",
  },
  {
    image: "/INDUSTRIA.jpg",
    text: "ESMALTE EPÓXICO INDUSTRIAL VERDE ",
    description: "",
    type: "Industrial",
    pdf: "/fichastecnicas/AnticorrosivosEpoxicos/FT AUTOIMPRIMANTE GRIS.pdf",
  },
  {
    image: "/INDUSTRIA.jpg",
    text: "FONDO  EPÓXICO ANTICORROSIVO NEGRO",
    description: "",
    type: "Industrial",
    pdf: "/fichastecnicas/AnticorrosivosEpoxicos/FT AUTOIMPRIMANTE GRIS.pdf",
  },
  {
    image: "/INDUSTRIA.jpg",
    text: "FONDO  EPÓXICO ANTICORROSIVO GRIS",
    description: "",
    type: "Industrial",
    pdf: "/fichastecnicas/AnticorrosivosEpoxicos/FT AUTOIMPRIMANTE GRIS.pdf",
  },
  {
    image: "/INDUSTRIA.jpg",
    text: "FONDO EPÓXICO ANTICORROSIVO BLANCO",
    description: "",
    type: "Industrial",
    pdf: "/fichastecnicas/AnticorrosivosEpoxicos/FT AUTOIMPRIMANTE GRIS.pdf",
  },
  {
    image: "/INDUSTRIA.jpg",
    text: "ESMALTE EPOXICO INDUSTRIAL GRIS OSCURO",
    description: "",
    type: "Industrial",
    pdf: "/fichastecnicas/AnticorrosivosEpoxicos/FT AUTOIMPRIMANTE GRIS.pdf",
  },
];

export default datosProductoIndustria;
