const datosProductoAuxiliares = [
  {
    image: "/AUXILIAR.jpg",
    text: "DILUYENTE PUR ATL",
    description: "",

    type: "SOLUCION EPOXICA",
    pdf: "/fichastecnicas/Barnices/FT BARNIZ HS.pdf",
  },
  {
    image: "/AUXILIAR.jpg",
    text: "DESENGRASANTE B.S",
    description: "",

    type: "Auxiliares",
    pdf: "/fichastecnicas/Barnices/FT BARNIZ PLUS 2K.pdf",
  },
  {
    image: "/AUXILIAR.jpg",
    text: "REMOVEDOR DE OXIDO Y ADHERENTE",
    description: "",
    type: "Auxiliares",
    pdf: "/fichastecnicas/Barnices/FT BARNIZ EXPRESS.pdf",
  },
  {
    image: "/AUXILIAR.jpg",
    text: "REMOVEDOR DE PINTURA",
    description: "",
    type: "Auxiliares",
    pdf: "/fichastecnicas/AnticorrosivosEpoxicos/FT AUTOIMPRIMANTE GRIS.pdf",
  },
  {
    image: "/AUXILIAR.jpg",
    text: "CATALIZADOR PUR 412",
    description: "",
    type: "Auxiliares",
    pdf: "/fichastecnicas/AnticorrosivosEpoxicos/FT AUTOIMPRIMANTE GRIS.pdf",
  },
  {
    image: "/AUXILIAR.jpg",
    text: "CATALIZADOR PUR 411",
    description: "",
    type: "Auxiliares",
    pdf: "/fichastecnicas/AnticorrosivosEpoxicos/FT AUTOIMPRIMANTE GRIS.pdf",
  },
  {
    image: "/AUXILIAR.jpg",
    text: "CATALIZADOR PUR 410",
    description: "",
    type: "Auxiliares",
    pdf: "/fichastecnicas/AnticorrosivosEpoxicos/FT AUTOIMPRIMANTE GRIS.pdf",
  },
  {
    image: "/AUXILIAR.jpg",
    text: "CATALIZADOR HS",
    description: "",
    type: "Auxiliares",
    pdf: "/fichastecnicas/AnticorrosivosEpoxicos/FT AUTOIMPRIMANTE GRIS.pdf",
  },
  {
    image: "/AUXILIAR.jpg",
    text: "CATALIZADOR WASH PRIMER",
    description: "",
    type: "Auxiliares",
    pdf: "/fichastecnicas/Diluyentesycomplementarios/FT DILUYENTE PUR ATL.pdf",
  },
  {
    image: "/AUXILIAR.jpg",
    text: "CATALIZADOR AUTOIMPRIMANTE",
    description: "",
    type: "Auxiliares",
    pdf: "/fichastecnicas/Diluyentesycomplementarios/FT DESENGRASANTE B.S.pdf",
  },
  {
    image: "/AUXILIAR.jpg",
    text: "CATALIZADOR EP 710",
    description: "",
    type: "Auxiliares",
    pdf: "/fichastecnicas/Diluyentesycomplementarios/FT REMOVEDOR DE OXIDO.pdf",
  },
  {
    image: "/AUXILIAR.jpg",
    text: "CATALIZADOR PUR IND",
    description: "",
    type: "Auxiliares",
    pdf: "/fichastecnicas/Diluyentesycomplementarios/FT SLN EPOXICA.pdf",
  },
  {
    image: "/MasillaAuxiliares.jpg",
    text: "MASILLA POLIESTER",
    description: "",
    type: "Auxiliares",
    pdf: "/fichastecnicas/Diluyentesycomplementarios/FT SOLUCIÓN POLIURETANICA.pdf",
  },
  {
    image: "/MasillaAuxiliares.jpg",
    text: "MASILLA DE RELLENO",
    description: "",
    type: "Auxiliares",
    pdf: "/fichastecnicas/AnticorrosivosEpoxicos/FT AUTOIMPRIMANTE GRIS.pdf",
  },
  {
    image: "/AUXILIAR.jpg",
    text: "ENDURECEDOR POLIURETANO",
    description: "",
    type: "Auxiliares",
    pdf: "/fichastecnicas/Entonadoresps/FT ENTONADORES PS.pdf",
  },
];

export default datosProductoAuxiliares;
